### PR TITLE
upping kitchen timeout for windows

### PR DESCRIPTION
**Pull request by vendoran**
Fixes Issue #26

### CODE REVIEW

**Comment by afiune** [comment]
@vendoran Nice! 🎉  Thank you for your PR... I was thinking maybe we can make this an property of the `delivery_test_kitchen` LWRP and set a default to the value you set. What do you think? 😄

**Comment by vendoran** [comment]
agreed having it adjustable would be better.

**Comment by afiune** [comment]
Do you think you can contribute with that? 🤓

**Comment by jvogt** [comment]
fyi, there is a missing comment on line 70.  I also agree it should be parameterized.

**Comment by PrajaktaPurohit** [comment]
closing in favor of #33

**Pull request closed without merging**
